targets:
  $default:
    builders:
      drift_dev:
        options:
          # Enable Drift managers
          generate_manager: true
          # Store dates as text for better compatibility
          store_date_time_values_as_text: true