name: ecommerce_api
description: E-commerce API built with Dart Frog.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.15.0
  sqlite3: ^2.1.0
  bcrypt: ^1.1.3
  jose: ^0.3.4  # For JWT handling
  uuid: ^4.0.0
  collection: ^1.18.0
  intl: ^0.18.1
  path: ^1.8.3
  # Required by dart_frog
  dart_jsonwebtoken: ^2.8.0
  shelf_cors_headers: ^0.1.5
  dart_frog: ^1.2.0
  dart_frog_cli: ^1.2.5

dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.6
  test: ^1.24.6